version: '3.1'
services:
  mysql:
    image: ${mysql_type}:${mysql_version}
    restart: always
    volumes:
      - ${mysql_local_storage_path}:/var/lib/mysql
    networks:
      - mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_root_password}"
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    networks:
      - mysql
    restart: always
    container_name: phpmyadmin
volumes:
  mysql_data:
networks:
  mysql: 
    external:
      name: mysql
    